import Head from "next/head";
import Link from "next/link";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";


function Login() {
    

  return (
    <>
      <Head>
        <title>CodeIT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.ico"
        />
        <link rel="icon" sizes="32x32" href="/favicon-32x32.ico" />
        <link rel="icon" sizes="16x16" href="/favicon-16x16.ico" />
      </Head>
      <Navbar />
      <button>Authenticate via Metamask</button>
      <Footer/>
    </>
  );
}

export default Login;